import Head from 'next/head';
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <Head>
      <script>tolstoyAppKey={'8424de39-0e47-47b1-807f-9416bcf48203'}</script>
      <script src="https://widget.gotolstoy.com/widget/widget.js" defer></script>
    </Head>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </>

  )
}
